import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";

import { AdoptionOverview } from "./AdoptionOverview";
import type { OrgSummaryCardData, OverviewSummaryResult } from "@/types/overview";

/**
 * OVW-01-TC-06 / OVW-01-TC-07 — the Adoption Overview page body.
 *
 * The populated fixture deliberately carries **no colour field of any kind**.
 * That is the point of the FR-2 assertion below, not an omission: the API
 * returns data only, and the client derives bar widths and legend colours
 * itself (D-06). If a future change started trusting a server-supplied
 * colour, this fixture would have none to give it.
 *
 * Assertions use plain vitest matchers (`toBeNull`, `toBe`, `toHaveLength`,
 * `.textContent`) -- this project deliberately wires up **no** `jest-dom`
 * matchers, a convention `ProgramDetailView.test.tsx` and `login/route.test.ts`
 * both call out explicitly. Do not reach for `toBeInTheDocument`.
 *
 * `vitest.config.ts` declares no `setupFiles`, so Testing Library's
 * auto-cleanup is NOT wired -- every test file unmounts explicitly in
 * `afterEach`, or renders accumulate across cases in the same file and
 * `getBy*` starts finding duplicates. Same idiom as `OrgSummaryCards.test.tsx`.
 */

afterEach(() => {
  cleanup();
});

// TC-06 fixture: 5 cards in mockup order, D-01 glyph/label literals, card 1
// carrying the ratio + the only non-null `sub` (D-02's 2026-09-10 correction).
const POPULATED_CARDS: OrgSummaryCardData[] = [
  { glyph: "▦", value: "7 / 10", label: "Programs using AI SDLC", sub: "70% adoption" },
  { glyph: "⬡", value: "12.5M", label: "Total token consumption", sub: null },
  { glyph: "</>", value: "850.0K", label: "Lines of code generated by Harness", sub: null },
  { glyph: "⤴", value: "42", label: "Releases using Harness", sub: null },
  { glyph: "❯", value: "18", label: "Repos with Harness installed", sub: null },
];

const POPULATED: OverviewSummaryResult = {
  status: "ok",
  data: {
    cards: POPULATED_CARDS,
    programs_using_ai: { count: 7, total: 10, adoption_percent: 70.0 },
  },
};

// TC-07: `adoption_percent` is null, NOT 0 -- the backend types it as a
// required nullable field precisely so this case stays distinguishable from a
// genuine zero. Passed through unchanged here; no `??`/`||` coalesce anywhere.
const ZERO_PROGRAMS: OverviewSummaryResult = {
  status: "ok",
  data: {
    cards: POPULATED_CARDS,
    programs_using_ai: { count: 0, total: 0, adoption_percent: null },
  },
};

describe("AdoptionOverview — populated (OVW-01-TC-06)", () => {
  it("renders all 5 summary cards with their glyph, value and label", () => {
    render(<AdoptionOverview result={POPULATED} />);

    const rendered = screen.getAllByTestId("org-summary-card");
    expect(rendered).toHaveLength(5);

    // Scoped to the cards rather than the whole document on purpose: card 1's
    // value ("7 / 10") is ALSO the adoption headline, because both derive from
    // the same count/total. That duplication is by design -- it is precisely
    // why OVW-01-FR-1 keeps `programs_using_ai` separate from `cards` -- so a
    // document-wide `queryByText` would find two nodes and fail.
    const cardText = rendered.map((el) => el.textContent ?? "");
    POPULATED_CARDS.forEach((card, i) => {
      expect(cardText[i]).toContain(card.glyph);
      expect(cardText[i]).toContain(card.value);
      expect(cardText[i]).toContain(card.label);
    });
  });

  it("shows card 1's ratio in both the card and the adoption headline (OVW-01-FR-1)", () => {
    render(<AdoptionOverview result={POPULATED} />);

    // The same count/total legitimately surfaces twice: as card 1's value and
    // as the indicator's headline. Asserted explicitly so the duplication is
    // recorded as intended rather than rediscovered as a bug.
    expect(screen.getAllByText("7 / 10")).toHaveLength(2);
  });

  it("renders the adoption headline, subtitle, 2 bar segments and 2 legend entries", () => {
    render(<AdoptionOverview result={POPULATED} />);

    expect(screen.getByTestId("adoption-headline").textContent).toBe("7 / 10");
    expect(screen.getByTestId("adoption-subtitle").textContent).toContain("70%");
    expect(screen.getAllByTestId("adoption-bar-segment")).toHaveLength(2);
    expect(screen.getAllByTestId("adoption-legend-entry")).toHaveLength(2);
  });

  it("derives every rendered colour client-side -- no colour crosses the wire (OVW-01-FR-2)", () => {
    render(<AdoptionOverview result={POPULATED} />);

    // The assertion that actually proves FR-2: gather every colour literal the
    // DOM ended up with, then show none of them could have come from the
    // response -- the fixture's own JSON contains no colour-bearing value at
    // all. A weaker test ("a colour is present") would pass either way.
    const serialisedFixture = JSON.stringify(POPULATED);
    const rendered = [
      ...screen.getAllByTestId("adoption-bar-segment"),
      ...screen.getAllByTestId("adoption-legend-entry"),
    ];
    const renderedColours = rendered
      .flatMap((el) => [
        el.getAttribute("style") ?? "",
        ...Array.from(el.querySelectorAll("*")).map(
          (child) => child.getAttribute("style") ?? "",
        ),
      ])
      .flatMap((style) => style.match(/#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)/g) ?? []);

    expect(renderedColours.length).toBeGreaterThan(0); // colours ARE applied...
    for (const colour of renderedColours) {
      // ...but none of them appears anywhere in the server payload.
      expect(serialisedFixture).not.toContain(colour);
    }
    expect(serialisedFixture).not.toMatch(/#[0-9a-fA-F]{3,8}|rgba?\(/);
    expect(serialisedFixture.toLowerCase()).not.toContain("color");
  });
});

describe("AdoptionOverview — zero programs (OVW-01-TC-07)", () => {
  it("renders 0/0 with a single bar segment and both legend counts at 0", () => {
    render(<AdoptionOverview result={ZERO_PROGRAMS} />);

    expect(screen.getByTestId("adoption-headline").textContent).toBe("0/0");
    expect(screen.getAllByTestId("adoption-bar-segment")).toHaveLength(1);

    const legend = screen.getAllByTestId("adoption-legend-entry");
    expect(legend).toHaveLength(2);
    for (const entry of legend) {
      expect(entry.textContent).toContain("0");
    }
  });

  it("invents no empty-state banner -- the mockup has none", () => {
    render(<AdoptionOverview result={ZERO_PROGRAMS} />);

    // The populated layout simply carries zero values (FR-4). Nothing in the
    // mockup offers empty-state copy, and CLAUDE.md forbids inventing UI it
    // does not show.
    expect(screen.queryByText(/no data/i)).toBeNull();
    expect(screen.queryByText(/nothing to show/i)).toBeNull();
    expect(screen.queryByText(/get started/i)).toBeNull();
    // ...and the summary cards still render, rather than being replaced.
    expect(screen.getAllByTestId("org-summary-card")).toHaveLength(5);
  });
});

describe("AdoptionOverview — non-ok statuses (OVW-01-AC-3, D-07)", () => {
  const MESSAGE = "You don't have access to this view.";

  it.each(["forbidden", "unauthorized", "error"] as const)(
    "renders the one generic error panel for status=%s, and no page content",
    (status) => {
      render(<AdoptionOverview result={{ status }} />);

      // Identical copy for all three is D-07's requirement, not duplication:
      // distinguishing them would leak whether the resource exists and
      // whether the session is at fault.
      expect(screen.queryByText(MESSAGE)).not.toBeNull();
      expect(screen.queryAllByTestId("org-summary-card")).toHaveLength(0);
      expect(screen.queryByTestId("adoption-headline")).toBeNull();
    },
  );
});
