import { afterEach, describe, expect, it } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";

import { OrgSummaryCards } from "./OrgSummaryCards";
import type { OrgSummaryCardData } from "@/types/overview";

afterEach(() => {
  cleanup();
});

// Mockup order (DESIGN.md Region 1) — order is part of the contract, asserted
// explicitly below, not merely rendered. Card 1 carries a `sub`
// (DECISIONS.md D-02); cards 2-5 ship `sub: null` per FR-1/D-02 today, but
// the component must render `sub` for whichever card carries one, not
// hardcode it to index 0 — so a second, non-index-0 `sub` case is also
// exercised via the dedicated "omitted, not rendered empty" test below.
const SAMPLE_CARDS: OrgSummaryCardData[] = [
  {
    glyph: "▦",
    value: "7 / 10",
    label: "Programs using AI SDLC",
    sub: "70% adoption",
  },
  { glyph: "⬡", value: "128.4K", label: "Total token consumption", sub: null },
  {
    glyph: "</>",
    value: "366K",
    label: "Lines of code generated by Harness",
    sub: null,
  },
  { glyph: "⤴", value: "128", label: "Releases using Harness", sub: null },
  {
    glyph: "❯",
    value: "54",
    label: "Repos with Harness installed",
    sub: null,
  },
];

describe("OrgSummaryCards (OVW-01-AC-5)", () => {
  it("renders the 5 cards in the exact backend order, glyph/value/label verbatim", () => {
    render(<OrgSummaryCards state="populated" cards={SAMPLE_CARDS} />);

    const cards = screen.getAllByTestId("org-summary-card");
    expect(cards).toHaveLength(5);

    // Order assertion: each card's rendered text, read in DOM order, must
    // match the input array's order exactly -- the component must not
    // re-sort or re-index the `cards` array.
    expect(cards.map((card) => card.textContent)).toEqual(
      SAMPLE_CARDS.map(
        (card) => `${card.glyph}${card.value}${card.label}${card.sub ?? ""}`,
      ),
    );
  });

  it("renders `sub` only for the card carrying one, omitted (not empty) for cards with sub: null", () => {
    render(<OrgSummaryCards state="populated" cards={SAMPLE_CARDS} />);

    const subs = screen.getAllByTestId("org-summary-card-sub");
    // Exactly one `sub` element exists -- the four `sub: null` cards render
    // no element at all (DESIGN.md's `sc-if` guard), not an empty one.
    expect(subs).toHaveLength(1);
    expect(subs[0].textContent).toBe("70% adoption");
  });

  it("renders 5 loading placeholders with no card text and no populated cards", () => {
    render(<OrgSummaryCards state="loading" />);

    const placeholders = screen.getAllByTestId(
      "org-summary-card-placeholder",
    );
    expect(placeholders).toHaveLength(5);
    placeholders.forEach((placeholder) => {
      expect(placeholder.textContent).toBe("");
    });
    expect(screen.queryByTestId("org-summary-card")).toBeNull();
    expect(screen.queryByTestId("org-summary-card-sub")).toBeNull();
  });
});
