import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";

import Page from "./page";
import shellStyles from "@/components/PersonaDashboardShell.module.css";
import type { OverviewSummaryResult } from "@/types/overview";

/**
 * `overview/page.tsx` tests (T-09) — the page-level composition harness for
 * `OVW-05-TC-01` (`docs/test-cases/OVW-05.json`) plus AC-5/AC-9 and the
 * condition 2a `redirect("/login")` regression.
 *
 * `@/lib/tokenStore`'s `callWithAuth` is replaced with a faithful fake that
 * actually invokes the supplied `makeRequest` with a fixed test access token
 * (matches `app/api/proxy/programs/route.test.ts`'s idiom) — so the two
 * concurrent `callWithAuth()` wrappers in `page.tsx` transparently forward to
 * whatever `@/lib/overviewApi`'s `fetchOverviewSummary` / `@/lib/meApi`'s
 * `fetchMe` are mocked to do. `SessionExpiredError` is re-exported from the
 * real module via `importOriginal`, so `page.tsx`'s own `instanceof` check in
 * its `catch` block matches genuinely rather than silently falling through.
 * `next/navigation`'s `redirect()` is mocked to throw (same idiom as
 * `app/login/page.test.tsx`): real `redirect()` works by throwing its own
 * `NEXT_REDIRECT` control-flow signal, and `page.tsx`'s own docstring states
 * that throw MUST propagate out of the `catch` block rather than being
 * swallowed.
 *
 * No `jest-dom` is wired in this project (`vitest.config.ts` has no
 * `setupFiles`) — assertions use plain vitest matchers, `.textContent`, and
 * `queryByRole`/`toBeNull()`, never `toBeInTheDocument()`. Every test
 * unmounts explicitly via `afterEach(cleanup)`.
 *
 * Several assertions below are scoped through `PersonaDashboardShell.module.css`
 * class names (`shellStyles`, matching `PersonaDashboardShell.test.tsx`'s own
 * idiom) rather than `screen.getByText`, because some rendered strings (e.g.
 * a persona whose `tag` and `jobTitle` are the identical literal `"Architect"`)
 * would otherwise match more than one node and make `getByText` ambiguous.
 */

const TEST_ACCESS_TOKEN = "test-access-token";

const { mockCallWithAuth, mockFetchOverviewSummary, mockFetchMe, mockRedirect } =
  vi.hoisted(() => ({
    mockCallWithAuth: vi.fn(),
    mockFetchOverviewSummary: vi.fn(),
    mockFetchMe: vi.fn(),
    mockRedirect: vi.fn(),
  }));

vi.mock("@/lib/tokenStore", async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...(actual as object),
    callWithAuth: mockCallWithAuth,
  };
});

vi.mock("@/lib/overviewApi", () => ({
  fetchOverviewSummary: mockFetchOverviewSummary,
}));

vi.mock("@/lib/meApi", () => ({
  fetchMe: mockFetchMe,
}));

vi.mock("next/navigation", () => ({
  redirect: (path: string) => {
    mockRedirect(path);
    throw new Error(`NEXT_REDIRECT:${path}`);
  },
}));

const { SessionExpiredError } = await import("@/lib/tokenStore");

// 5-card OK fixture, D-01 glyph/label literals — same fixture
// `AdoptionOverview.test.tsx` (OVW-01-TC-06) already validates in isolation;
// reused here only to prove the summary region renders unaffected while
// `persona`/`signedInUser` vary, not to re-exercise its own rendering rules.
const OVERVIEW_SUMMARY_OK: OverviewSummaryResult = {
  status: "ok",
  data: {
    cards: [
      { glyph: "▦", value: "7 / 10", label: "Programs using AI SDLC", sub: "70% adoption" },
      { glyph: "⬡", value: "12.5M", label: "Total token consumption", sub: null },
      { glyph: "</>", value: "850.0K", label: "Lines of code generated by Harness", sub: null },
      { glyph: "⤴", value: "42", label: "Releases using Harness", sub: null },
      { glyph: "❯", value: "18", label: "Repos with Harness installed", sub: null },
    ],
    programs_using_ai: { count: 7, total: 10, adoption_percent: 70.0 },
  },
};

beforeEach(() => {
  mockCallWithAuth.mockImplementation(
    async (makeRequest: (accessToken: string) => unknown) =>
      makeRequest(TEST_ACCESS_TOKEN),
  );
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("OVW-05-TC-01 — jobTitle is composed from PERSONA_DISPLAY, never passed through from GET /api/me", () => {
  it("renders 'Chief Information Officer', never the decoy 'Chief Backend Engineer' the mocked response carries", async () => {
    mockFetchOverviewSummary.mockResolvedValue(OVERVIEW_SUMMARY_OK);
    // The extra `jobTitle` key simulates a hypothetical pass-through bug —
    // the real, `extra="forbid"` GET /api/me response model would never
    // emit it (test_data.me_response_decoy_job_title_key, TC-01).
    mockFetchMe.mockResolvedValue({
      status: "ok",
      data: {
        name: "Elena Vasquez",
        persona: "cio",
        jobTitle: "Chief Backend Engineer",
      },
    });

    const { container } = render(await Page());

    const jobTitleEl = container.getElementsByClassName(shellStyles.jobTitle)[0];
    expect(jobTitleEl.textContent).toBe("Chief Information Officer");

    // The decoy value must appear nowhere in the rendered output at all —
    // not just absent from the job-title node specifically.
    expect(document.body.textContent).not.toContain("Chief Backend Engineer");
  });
});

describe("AC-5/AC-9 — persona/signedInUser reach the shell from GET /api/me, never a hardcoded literal", () => {
  it("renders the CIO identity block (name + initials avatar) and org header (title/pill/subtitle)", async () => {
    mockFetchOverviewSummary.mockResolvedValue(OVERVIEW_SUMMARY_OK);
    mockFetchMe.mockResolvedValue({
      status: "ok",
      data: { name: "Elena Vasquez", persona: "cio" },
    });

    const { container } = render(await Page());

    expect(
      container.getElementsByClassName(shellStyles.name)[0].textContent,
    ).toBe("Elena Vasquez");
    expect(
      container.getElementsByClassName(shellStyles.avatar)[0].textContent,
    ).toBe("EV");

    expect(
      container.getElementsByClassName(shellStyles.pageTitle)[0].textContent,
    ).toBe("Adoption Overview");
    expect(
      container.getElementsByClassName(shellStyles.orgPill)[0].textContent,
    ).toBe("CIO / CXO");
    expect(
      container.getElementsByClassName(shellStyles.orgSubtitle)[0]
        .textContent,
    ).toBe("Organization-wide AI-in-SDLC adoption, spend & impact");
  });

  it("passes through whatever persona GET /api/me resolves — never a hardcoded persona='cio' literal (NFR-Security)", async () => {
    mockFetchOverviewSummary.mockResolvedValue(OVERVIEW_SUMMARY_OK);
    mockFetchMe.mockResolvedValue({
      status: "ok",
      data: { name: "Sam Rivera", persona: "architect" },
    });

    const { container } = render(await Page());

    // A hardcoded `persona="cio"` would render "CIO / CXO" regardless of
    // this mocked response — asserting the ACTUAL resolved persona's tag
    // proves the value is threaded through, not fixed.
    expect(
      container.getElementsByClassName(shellStyles.orgPill)[0].textContent,
    ).toBe("Architect");
    expect(
      container.getElementsByClassName(shellStyles.jobTitle)[0].textContent,
    ).toBe("Architect");
    expect(
      container.getElementsByClassName(shellStyles.name)[0].textContent,
    ).toBe("Sam Rivera");
    expect(screen.queryByText("CIO / CXO")).toBeNull();
  });
});

describe("Condition 2a regression — a SessionExpiredError from EITHER call still redirects to /login", () => {
  it("redirects when the GET /api/overview/summary call throws SessionExpiredError", async () => {
    mockFetchOverviewSummary.mockRejectedValue(
      new SessionExpiredError("refresh failed"),
    );
    mockFetchMe.mockResolvedValue({
      status: "ok",
      data: { name: "Elena Vasquez", persona: "cio" },
    });

    await expect(Page()).rejects.toThrow("NEXT_REDIRECT");

    expect(mockRedirect).toHaveBeenCalledTimes(1);
    expect(mockRedirect).toHaveBeenCalledWith("/login");
  });

  it("redirects when the GET /api/me call throws SessionExpiredError", async () => {
    mockFetchOverviewSummary.mockResolvedValue(OVERVIEW_SUMMARY_OK);
    mockFetchMe.mockRejectedValue(new SessionExpiredError("refresh failed"));

    await expect(Page()).rejects.toThrow("NEXT_REDIRECT");

    expect(mockRedirect).toHaveBeenCalledTimes(1);
    expect(mockRedirect).toHaveBeenCalledWith("/login");
  });
});

describe("D-03 sentinel — a failed GET /api/me degrades persona display only, never the page into an error page", () => {
  it("renders the summary content normally while the shell shows the neutral 'Persona unavailable' badge, and no OverviewErrorPanel", async () => {
    mockFetchOverviewSummary.mockResolvedValue(OVERVIEW_SUMMARY_OK);
    mockFetchMe.mockResolvedValue({ status: "forbidden" });

    const { container } = render(await Page());

    // The overview-summary result is unaffected by the failed /api/me call.
    expect(screen.getAllByTestId("org-summary-card")).toHaveLength(5);
    expect(screen.getByTestId("adoption-headline").textContent).toBe(
      "7 / 10",
    );

    // persona degraded to the resolver-error sentinel -> the shell's
    // existing neutral badge, not a new error UI.
    expect(screen.getByText("Persona unavailable").textContent).toBe(
      "Persona unavailable",
    );

    // signedInUser is undefined -> the neutral avatar fallback, no name text.
    expect(container.querySelector('[aria-hidden="true"]')).not.toBeNull();
    expect(container.getElementsByClassName(shellStyles.name)).toHaveLength(
      0,
    );

    // A failed /api/me must NOT turn this into an error page.
    expect(
      screen.queryByText("You don't have access to this view."),
    ).toBeNull();
  });
});
